
// send get request for all blogs
GET http://localhost:3003/api/blogs

###

// get request for a single blog
GET http://localhost:3003/api/blogs/id

###

// send post request for a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "how i test my backend",
  "author": "steven segfault",
  "url": "example.com/test",
  "likes": 24,
  "userID": "6456eba991a1266cf91347d7"
}

###

PUT http://localhost:3003/api/blogs/id
Content-Type: application/json

{
  "title": "wednesday test updated",
  "author": "jason yu sumpter",
  "url": "serve.com/yaas",
  "likes": 50
}

###

// send delete request for a blog
DELETE http://localhost:3003/api/blogs/id